### ISSUE TITLE
"lib/eeprom32_rotate" needs to be updated

### ISSUE THREAD

**Issue by mnltake** [eringerli/esp32-aog#4]
I got an error about eeprom32_rotate when trying to build.

https://github.com/xoseperez/eeprom32_rotate/tree/master

> NOTICE: Please note EEPROM emulation in the ESP32 is no longer maintained and only supported for backwards compatibility. Moreover, the latest 1.0.3 SDK version breaks this library. Therefore, this library will no longer be maintained either.

**Comment by doppelgrau** [comment]
Dirty Hack: use old versions: https://github.com/doppelgrau/esp32-aog/blob/quickAndDirtyPoC/platformio.ini

Better: Change storage of settings (e.g. Preferences.h), but that's a major rewrite

**Comment by doppelgrau** [comment]
Update: Rewrite is making progress, should be usable in a few days: https://github.com/doppelgrau/esp32-aog/tree/Cleanup

**Comment by eringerli** [comment]
Closing, as this dependency is removed. Now, the config is saved as a JSON.
